### ISSUE TITLE
ttest degrees of freedom miscalculation

### ISSUE THREAD

**Issue by Chantel-B** [researchpy/researchpy#11]
It appears to me that the  Welch-Satterthwaite Degrees of Freedom on line 61 of ttest.py is incorrect - the current line is:

`dof = -2 + (((group1.var()/group1.count()) + (group2.var()/group2.count()))**2 / ((group1.var()/group1.count())**2 / (group1.count()+1) + (group2.var()/group2.count())**2 / (group2.count()+1)))`

but it should be:

`dof = (((group1.var()/group1.count()) + (group2.var()/group2.count()))**2 / ((group1.var()/group1.count())**2 / (group1.count()-1) + (group2.var()/group2.count())**2 / (group2.count()-1)))`

a source: [https://www.statology.org/welchs-t-test/](url)
Current calculations disagree with output from R and StatCrunch

**Comment by Corey-Bryant** [comment]
Hey! Thanks for reaching out and reporting a suspected issue. 

The formula currently used in ResearchPy is from Welch (1947) and is the default in Stata. If you were to compare the output from ResearchPy and Stata the results would be identical. The formula used in R uses the Satterthwaite (1946) calculation. I do know that my note in my code file state's the Welch-Satterthwaite which has been corrected in the upcoming version release. 

Given this conversation, and since I am still developing the next version, I will add the ability to specify which DoF one wants calculated.


Thank you for your time and envolvement,

Corey




Welch, B.L. (1947). "The generalization of "Student's" problem when several different population variances are involved". Biometrika, 34, 1/2, pp. 28–35.

Satterthwaite, F.E. (1946). "An Approximate Distribution of Estimates of Variance Components". Biometrics Bulletin, 2, 6, pp. 110–114.

**Comment by Chantel-B** [comment]
Thank you! That's super helpful. I haven't used Stata before and I've only ever seen the Satterthwaite formula; but I am also not a statistician! Thanks for the quick response and clarification.

**Comment by Chantel-B** [comment]
One more question - If I'm following correctly, you use the scipy.statst.ttest_ind to determine the p-value. I can't find in the scipy documentation what degrees of freedom is used to find the p-value for the unequal variances case. But they do say they're using the Welch's test with a link to the wikipedia page [https://en.wikipedia.org/wiki/Welch%27s_t-test](url) with the Satterthwaite formula (If that's the one that I thought it should be originally - I'm honestly not sure if I'm referencing them correctly now) for dof. Do you know if the formula you use for degrees of freedom matches the degrees of freedom used by scipy to calculate the p-value? Or "should" the researchpy p-value be slightly smaller than the scipy value if it is using a slightly higher value for degrees of freedom? I hope I'm making sense :-S

**Comment by Chantel-B** [comment]
OK - this is an example of what I was wondering and it does seem the degrees of freedom from researchpy is not the same degrees of freedom being used by scipy to calculate the p-value from the t-distribution:

`import pandas as pd`
`from scipy.stats import ttest_ind`
`from scipy.stats import t`
`import researchpy as rp`

`#sample data sets that have a small size and slightly similar variability to force a small t-statistic to see differences in p-values based on degrees of freedom from different packages`
`df1=pd.DataFrame({'sample1': [3, 3, 2, 1, 2, 3]})`
`df2=pd.DataFrame({"sample2": [3,3,2,2,1,1,1,1,1,1]})`

`#independent t-statistic and p-value from scipy (unequal variances)`
`tstat, pval = ttest_ind(df1.sample1,df2.sample2,equal_var=False)`

`#degrees of freedom and p-value from researchpy (unequal variances)`
`rpdof = rp.ttest(df1.sample1,df2.sample2,"sample1","sample2",equal_variances=False)[1].results[1]`
`rppval = rp.ttest(df1.sample1,df2.sample2,"sample1","sample2",equal_variances=False)[1].results[3]`

`#degrees of freedom with n-1 instead of value from researchpy`
`dof = (((df1.sample1.var()/df1.sample1.count()) + (df2.sample2.var()/df2.sample2.count()))**2 / ((df1.sample1.var()/df1.sample1.count())**2 / (df1.sample1.count()-1) + (df2.sample2.var()/df2.sample2.count())**2 / (df2.sample2.count()-1)))`



`#two-sided p-value from t-distribution using n-1 degrees of freedom formula`
`2*(1-t.cdf(tstat,dof))`
0.11390872809965691

`#two-sided p-value from t-distribution using researchpy degrees of freedom value`
`2*(1-t.cdf(tstat,rpdof))`
0.10964159278193275

`#p-value from scipy matches two-sided p-value from t-distribution using n-1 degrees of freedom formula`
`pval`
0.11390872809965696

`#p-value from researchpy agrees with the p-value from scipy and t-distribution from n-1 degrees of freedom formula`
`rppval`
0.1139

thanks again for your responsiveness to my first experience on github as a registered user! I appreciate your researchpy package and am using it in my lab for data science students that are also taking my statistical methods course.

**Comment by Corey-Bryant** [comment]
Morning,

Happy to be apart of your first experience as a registered user on GitHub! That's exciting to here and I appreciate your use and involvement, particularly the deep diving into the opensource of the code! It absolutely helps ensure packages are strong and correct and why I made my package opensource; it's a passion project I develop in my free time and highly appreciate community involvement.

I was wanted to respond so you know that I saw these messages and will be able to respond a bit later today to the code and whatnot.

Best,

Corey

**Comment by Corey-Bryant** [comment]
Hey Chantel,

I dove into my code and the references I was using while developing this and you are correct. In an earlier version I used the Welch-Satterthwaite degrees of freedom and switched to the Welch degrees of freedom to match Stata. During this switch it appears the calculation for p-value using the Welch's degrees of freedom was not pushed through.

At the end of this month a new version of ResearchPy will be releasing with this correction and more methods. Like I mentioned  earlier in our conversation, I will add the option where one can select which method of the Welch's test they want to calculate. I will be sure to credit your help with this. If you want your name credited please email at CoreyBryant10@gmail.com, otherwise I will use your GitHub account name.


Thank you for your use and engagement,

Corey
