### ISSUE TITLE
Paired ttest Cohen's D calculation

### ISSUE THREAD

**Issue by oas01** [researchpy/researchpy#17]
The Cohen's D calculation for the paired ttest calculation doesn't appear consistent with the documentation. 

The calculation is currently:

`d = (group1.mean() - group2.mean()) / ((group1.std() + group2.std()) / 2)`

using the mean of the standard deviations, where I believe it should be:

`d = (group1.mean() - group2.mean()) / diff.std()`

using the standard deviation of the differences.

A source: https://rcompanion.org/handbook/I_04.html

**Comment by Corey-Bryant** [comment]
Thank you for raising this, and the update to the documentation was missed for `paired ttest` but was for `difference_test ` when calculating a paired t-test. There was a change in calculating Cohen's D for paired t-tests from Cohen's D to Cohen's D_av which was do to peer-review research on the effect size measure and arguments of concern that Cohen's D overestimating the effect for correlated samples which Cohen's D_av addresses.

Instead of supporting just one, in the next update both will be supported and the documentation will reflect.
